---
title: "Localized Impact Map"
output: html_document
date: "2023-03-24"
---

<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">


```{css, echo=FALSE}

h1.title {
  font-family: roboto;
  color: transparent;
  font-weight: 700;
  text-align: left;
  font-size: 12px;
  padding: 0px;
}
    
.leaflet-control-search .search-button {
        display:none;
}

.leaflet-control-search .search-input {
        display: block;
        float: left;
        border: 3px solid #00215C;
        border-radius: 5px;
        width: 300px;
        height: 30px;
        font-family: roboto;
        font-weight: 400;
        font-size: 18px;
        padding: 0 18px 0 2px;
        margin:0px 0 0px 0px
}

.nav-pills > li.active > a, .nav-pills > li.active > a:focus, .nav-pills > li.active > a:hover {
    color: #fff;
    background-color: darkblue;
}

a {
    color: darkblue;
    text-decoration: none;
}

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Testing unstyled tabs for switching maps {.tabset .tabset-pills}

### Flood
```{r goofy, out.width='100%', echo=FALSE}
floodmap
```

### Heat
```{r silly, out.width='100%', echo=FALSE}
heatmap
```

### Wind
```{r silly2, out.width='100%', echo=FALSE}
windmap
```

### Wildfire
```{r silly3, out.width='100%', echo=FALSE}
firemap
```

## {-}




## R Markdown

Test text

```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

